name: Build ExecutorchCoreML Wheel

on:
  push:
    branches:
      - main

jobs:
  Build-coreml-wheel:
    runs-on: macos-latest
    environment: prod-deploy
    permissions: 
      contents: write 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup for CoreML delegate
        shell: bash
        run: ./executorch/backends/apple/coreml/scripts/install_requirements.sh
      
      - name: Install Setup Tools
        shell: bash
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build ExecutorchCoreML Wheel
        shell: bash
        run: |
          ./build_executorchcoreml_wheel.sh &&\
          ls -la
      
      - name: Archive the wheel
        run: |
          zip -r executorchcoreml-wheel.zip out-coreml-wheel
      
      - name: Set the tag from TAG file to environment variable
        run: |
          export TAG=$(cat TAG)
          echo "TAG: $TAG"
          echo "TAG=${TAG}" >> $GITHUB_ENV
      
      - name: Upload executorchcoreml wheel
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: executorchcoreml-wheel.zip
          tag_name: ${{ env.TAG }}-wheel

